### ISSUE TITLE
Improve User Experience: Implement a Loading Page for the App

### ISSUE THREAD

**Issue by Mr-RiVi** [Agri-Vision/frontend#1]
### Objective:
Develop a loading page to improve user experience during data processing and app loading times.

### Current Implementation:
* Loading Page Component: Located in src/pages/Loading.tsx.
* CSS Stylesheet: Located in src/assets/styles/loading.css.

### Task:
Replace the existing loading page with a newly designed one that incorporates enhanced features and is suitable for our application.

### Design Requirements:
Ensure the design is responsive and works on various devices.

### Technical Considerations:
Ensure the loading page does not significantly impact performance.

**Comment by it21055294** [comment]
Successfully update the loading functionality in the system, integrating a drone rotation as the loader.
